import { ShaderChunk } from 'three';
import { CompileGraphResult, ThreeNodeInfo } from '../../graph/graph';
import { Graph } from '../../graph/graph-types';
import { nodeName } from '../../graph/graph';
import { threeInjectionMaps, stringifyThreeValue } from './threngine';
import { EngineNodeType } from '../../engine';

export type ThreeExportInput = {
  fragmentResult: string;
  vertexResult: string;
  compileResult: CompileGraphResult;
  graph: Graph;
  userUniforms: Record<string, { value: any; type?: string }>;
  shaderName: string;
};

const extractUniformDeclarations = (glsl: string): string =>
  glsl
    .split('\n')
    .filter((l) => l.trimStart().startsWith('uniform '))
    .join('\n');

const stripUniformDeclarations = (glsl: string): string =>
  glsl
    .split('\n')
    .filter((l) => !l.trimStart().startsWith('uniform '))
    .join('\n');

const stripGlslPreamble = (glsl: string): string =>
  glsl
    .replace(/^#version \d+ es\s*\n?/m, '')
    .replace(/^\s*precision\s+\w+p\s+\w+;\s*\n?/gm, '');

const serializeUniforms = (
  uniforms: Record<string, { value: any; type?: string }>
): string => {
  const entries = Object.entries(uniforms).map(([name, { value }]) => {
    const valStr = stringifyThreeValue(value);
    return `    ${name}: { value: ${valStr} }`;
  });
  return `{\n${entries.join(',\n')}\n  }`;
};

const updateLines = (
  uniforms: Record<string, { value: any; type?: string }>
): string => `      // uniforms.iTime.value += delta;\n`;

const generateType1Export = (input: ThreeExportInput): string => {
  const { fragmentResult, vertexResult, userUniforms, shaderName } = input;
  const uniformsStr = serializeUniforms(userUniforms);

  return `// Generated by Shaderfrog — ${shaderName}
import * as THREE from 'three';

export function createMaterial() {
  const uniforms = ${uniformsStr};

  const material = new THREE.ShaderMaterial({
    uniforms,
    vertexShader: ${JSON.stringify(vertexResult.replace(/^#version \d+ es\s*\n?/m, ''))},
    fragmentShader: ${JSON.stringify(fragmentResult.replace(/^#version \d+ es\s*\n?/m, ''))},
  });

  return {
    material,
    update(delta) {
${updateLines(userUniforms)}    },
  };
}
`;
};

const generateType2Export = (input: ThreeExportInput): string => {
  const { fragmentResult, vertexResult, compileResult, graph, userUniforms, shaderName } =
    input;
  const { threeNode } = compileResult;
  if (!threeNode) return generateType1Export(input);

  const MatClassName: Record<string, string> = {
    [EngineNodeType.physical]: 'MeshPhysicalMaterial',
    [EngineNodeType.phong]: 'MeshPhongMaterial',
    [EngineNodeType.toon]: 'MeshToonMaterial',
  };

  const matClass = MatClassName[threeNode.nodeType] ?? 'MeshPhysicalMaterial';
  const injectionMap = threeInjectionMaps[threeNode.nodeType];

  const forcingProps: string[] = [];
  const fragChunkReplacements: Array<{ includeStr: string; modifiedChunk: string }> = [];
  const vertChunkReplacements: Array<{ includeStr: string; modifiedChunk: string }> = [];

  for (const filler of threeNode.connectedFillers) {
    const fromNode = graph.nodes.find((n) => n.id === filler.fromNodeId);
    const callExpr = fromNode ? `${nodeName(fromNode)}()` : 'sfFragmentEntry()';
    const vertCallExpr = fromNode ? `${nodeName(fromNode)}()` : 'sfVertexEntry()';

    const fragPoint = injectionMap?.fragment?.[filler.fillerName];
    if (fragPoint?.forceProperty) {
      forcingProps.push(`  mat.${fragPoint.forceProperty} = new THREE.Texture();`);
    }
    if (fragPoint) {
      const chunkSource = ShaderChunk[fragPoint.chunk as keyof typeof ShaderChunk];
      if (chunkSource) {
        const modifiedChunk = chunkSource.replace(
          fragPoint.find,
          fragPoint.replace(callExpr)
        );
        fragChunkReplacements.push({
          includeStr: `#include <${fragPoint.chunk}>`,
          modifiedChunk,
        });
      }
    }

    const vertPoint = injectionMap?.vertex?.[filler.fillerName];
    if (vertPoint) {
      const chunkSource = ShaderChunk[vertPoint.chunk as keyof typeof ShaderChunk];
      if (chunkSource) {
        const modifiedChunk = chunkSource.replace(
          vertPoint.find,
          vertPoint.replace(vertCallExpr)
        );
        vertChunkReplacements.push({
          includeStr: `#include <${vertPoint.chunk}>`,
          modifiedChunk,
        });
      }
    }
  }

  const cleanFrag = stripGlslPreamble(fragmentResult);
  const fragUniformDecls = extractUniformDeclarations(cleanFrag);
  const fragFunctions = stripUniformDeclarations(cleanFrag);
  const cleanVert = stripGlslPreamble(vertexResult);
  const vertFunctions = stripUniformDeclarations(cleanVert);
  const uniformsStr = serializeUniforms(userUniforms);

  const fragReplCode = fragChunkReplacements
    .map(
      ({ includeStr, modifiedChunk }) =>
        `    shader.fragmentShader = shader.fragmentShader.replace(\n      ${JSON.stringify(includeStr)},\n      ${JSON.stringify(modifiedChunk)}\n    );`
    )
    .join('\n');

  const vertReplCode = vertChunkReplacements
    .map(
      ({ includeStr, modifiedChunk }) =>
        `    shader.vertexShader = shader.vertexShader.replace(\n      ${JSON.stringify(includeStr)},\n      ${JSON.stringify(modifiedChunk)}\n    );`
    )
    .join('\n');

  const fragUniformsLine = fragUniformDecls.trim()
    ? `    shader.fragmentShader = ${JSON.stringify(fragUniformDecls + '\n')} + shader.fragmentShader;`
    : '';
  const fragFnsLine = fragFunctions.trim()
    ? `    shader.fragmentShader = shader.fragmentShader.replace('void main() {', ${JSON.stringify(fragFunctions + '\nvoid main() {')} );`
    : '';
  const vertFnsLine = vertFunctions.trim()
    ? `    shader.vertexShader = shader.vertexShader.replace('void main() {', ${JSON.stringify(vertFunctions + '\nvoid main() {')} );`
    : '';

  return `// Generated by Shaderfrog — ${shaderName}
import * as THREE from 'three';

export function createMaterial() {
  const uniforms = ${uniformsStr};

  const mat = new THREE.${matClass}();
${forcingProps.join('\n')}

  mat.onBeforeCompile = (shader) => {
${fragUniformsLine}
${fragFnsLine}
${fragReplCode}
${vertFnsLine}
${vertReplCode}
    Object.assign(shader.uniforms, uniforms);
  };

  return {
    material: mat,
    update(delta) {
${updateLines(userUniforms)}    },
  };
}
`;
};

export const generateThreeExport = (input: ThreeExportInput): string => {
  const { threeNode } = input.compileResult;
  return threeNode ? generateType2Export(input) : generateType1Export(input);
};
